/* $Id$ */

/** @file src/table/structureinfo.c Structure file tables. */

#include <stdio.h>
#include "types.h"

#include "../structure.h"

StructureInfo g_table_structureInfo[] = {
	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 232,
		/* name                 */ "Concrete",
		/* stringID_full        */ 233,
		/* wsa                  */ "slab.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ true,
		/* variable_0008        */ true,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ false,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 0,
		/* hitpoints            */ 20,
		/* fogUncoverRadius     */ 1,
		/* spriteID             */ 65,
		/* buildCredits         */ 5,
		/* buildTime            */ 16,
		/* availableCampaign    */ 1,
		/* structuresRequired   */ 0,
		/* sortPriority         */ 2,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 2,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 5,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 0,
		/* layout               */ 0,
		/* iconGroup            */ 8,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C71 } },
		/* [1]                  */ { { 0x0, 0x2C71 } },
		/* [2]                  */ { { 0x0, 0x2C71 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 234,
		/* name                 */ "Concrete4",
		/* stringID_full        */ 235,
		/* wsa                  */ "4slab.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ true,
		/* variable_0008        */ true,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ false,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 0,
		/* hitpoints            */ 20,
		/* fogUncoverRadius     */ 1,
		/* spriteID             */ 83,
		/* buildCredits         */ 20,
		/* buildTime            */ 16,
		/* availableCampaign    */ 4,
		/* structuresRequired   */ 0,
		/* sortPriority         */ 4,
		/* upgradeLevelRequired */ 1,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 2,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 10,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 0,
		/* layout               */ 3,
		/* iconGroup            */ 8,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C71 } },
		/* [1]                  */ { { 0x0, 0x2C71 } },
		/* [2]                  */ { { 0x0, 0x2C71 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 236,
		/* name                 */ "Palace",
		/* stringID_full        */ 237,
		/* wsa                  */ "palace.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ false,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 128,
		/* hitpoints            */ 1000,
		/* fogUncoverRadius     */ 5,
		/* spriteID             */ 66,
		/* buildCredits         */ 999,
		/* buildTime            */ 130,
		/* availableCampaign    */ 8,
		/* structuresRequired   */ 2048,
		/* sortPriority         */ 5,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 3,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 400,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 80,
		/* layout               */ 6,
		/* iconGroup            */ 11,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C74 } },
		/* [1]                  */ { { 0x0, 0x2C74 } },
		/* [2]                  */ { { 0x0, 0x2C74 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 238,
		/* name                 */ "Light Fctry",
		/* stringID_full        */ 239,
		/* wsa                  */ "liteftry.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ true,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 64,
		/* hitpoints            */ 350,
		/* fogUncoverRadius     */ 3,
		/* spriteID             */ 67,
		/* buildCredits         */ 400,
		/* buildTime            */ 96,
		/* availableCampaign    */ 3,
		/* structuresRequired   */ 4608,
		/* sortPriority         */ 14,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 4,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 200,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 20,
		/* layout               */ 3,
		/* iconGroup            */ 12,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C82 } },
		/* [1]                  */ { { 0x0, 0x2C83 } },
		/* [2]                  */ { { 0x0, 0x2C84 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ 13,
		/* [1]                  */ 15,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 3,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 240,
		/* name                 */ "Heavy Fctry",
		/* stringID_full        */ 241,
		/* wsa                  */ "hvyftry.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ true,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 64,
		/* hitpoints            */ 200,
		/* fogUncoverRadius     */ 3,
		/* spriteID             */ 68,
		/* buildCredits         */ 600,
		/* buildTime            */ 144,
		/* availableCampaign    */ 4,
		/* structuresRequired   */ 262664,
		/* sortPriority         */ 28,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 5,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 600,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 35,
		/* layout               */ 5,
		/* iconGroup            */ 13,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C7E } },
		/* [1]                  */ { { 0x0, 0x2C7F } },
		/* [2]                  */ { { 0x0, 0x2C80 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ 10,
		/* [1]                  */ 7,
		/* [2]                  */ 16,
		/* [3]                  */ 9,
		/* [4]                  */ 11,
		/* [5]                  */ 8,
		/* [6]                  */ 17,
		/* [7]                  */ 12,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 4,
		/* [1]                  */ 5,
		/* [2]                  */ 6,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 242,
		/* name                 */ "Hi-Tech",
		/* stringID_full        */ 243,
		/* wsa                  */ "hitcftry.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ true,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 64,
		/* hitpoints            */ 400,
		/* fogUncoverRadius     */ 3,
		/* spriteID             */ 69,
		/* buildCredits         */ 500,
		/* buildTime            */ 120,
		/* availableCampaign    */ 5,
		/* structuresRequired   */ 262664,
		/* sortPriority         */ 30,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 6,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 200,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 35,
		/* layout               */ 5,
		/* iconGroup            */ 14,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C79 } },
		/* [1]                  */ { { 0x0, 0x2C7A } },
		/* [2]                  */ { { 0x0, 0x2C7C } }
		},
		{ /* buildableUnits */
		/* [0]                  */ 0,
		/* [1]                  */ 1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 7,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 244,
		/* name                 */ "IX",
		/* stringID_full        */ 245,
		/* wsa                  */ "ix.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ false,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 192,
		/* hitpoints            */ 400,
		/* fogUncoverRadius     */ 3,
		/* spriteID             */ 70,
		/* buildCredits         */ 500,
		/* buildTime            */ 120,
		/* availableCampaign    */ 7,
		/* structuresRequired   */ 6656,
		/* sortPriority         */ 34,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 7,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 100,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 40,
		/* layout               */ 3,
		/* iconGroup            */ 15,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C8A } },
		/* [1]                  */ { { 0x0, 0x2C8A } },
		/* [2]                  */ { { 0x0, 0x2C8A } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 246,
		/* name                 */ "WOR",
		/* stringID_full        */ 247,
		/* wsa                  */ "wor.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ true,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ false,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 128,
		/* hitpoints            */ 400,
		/* fogUncoverRadius     */ 3,
		/* spriteID             */ 71,
		/* buildCredits         */ 400,
		/* buildTime            */ 104,
		/* availableCampaign    */ 5,
		/* structuresRequired   */ 263680,
		/* sortPriority         */ 20,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 8,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 175,
		/* availableHouse       */ 61,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 20,
		/* layout               */ 3,
		/* iconGroup            */ 16,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C8B } },
		/* [1]                  */ { { 0x0, 0x2C8B } },
		/* [2]                  */ { { 0x0, 0x2C8B } }
		},
		{ /* buildableUnits */
		/* [0]                  */ 5,
		/* [1]                  */ 3,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 6,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 248,
		/* name                 */ "Const Yard",
		/* stringID_full        */ 249,
		/* wsa                  */ "construc.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ true,
		/* notused_0004         */ false,
		/* variable_0008        */ true,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 64,
		/* hitpoints            */ 400,
		/* fogUncoverRadius     */ 3,
		/* spriteID             */ 72,
		/* buildCredits         */ 400,
		/* buildTime            */ 80,
		/* availableCampaign    */ 99,
		/* structuresRequired   */ -1,
		/* sortPriority         */ 0,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 9,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 300,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 0,
		/* layout               */ 3,
		/* iconGroup            */ 17,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C8C } },
		/* [1]                  */ { { 0x0, 0x2C8C } },
		/* [2]                  */ { { 0x0, 0x2C8C } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 4,
		/* [1]                  */ 6,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 250,
		/* name                 */ "Windtrap",
		/* stringID_full        */ 251,
		/* wsa                  */ "windtrap.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 64,
		/* hitpoints            */ 200,
		/* fogUncoverRadius     */ 2,
		/* spriteID             */ 73,
		/* buildCredits         */ 300,
		/* buildTime            */ 48,
		/* availableCampaign    */ 1,
		/* structuresRequired   */ 0,
		/* sortPriority         */ 6,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 10,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 300,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ -100,
		/* layout               */ 3,
		/* iconGroup            */ 19,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C92 } },
		/* [1]                  */ { { 0x0, 0x2C92 } },
		/* [2]                  */ { { 0x0, 0x2C92 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 252,
		/* name                 */ "Barracks",
		/* stringID_full        */ 253,
		/* wsa                  */ "barrac.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ true,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ false,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 128,
		/* hitpoints            */ 300,
		/* fogUncoverRadius     */ 2,
		/* spriteID             */ 74,
		/* buildCredits         */ 300,
		/* buildTime            */ 72,
		/* availableCampaign    */ 2,
		/* structuresRequired   */ 262656,
		/* sortPriority         */ 18,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 11,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 100,
		/* availableHouse       */ 62,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 10,
		/* layout               */ 3,
		/* iconGroup            */ 18,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C94 } },
		/* [1]                  */ { { 0x0, 0x2C94 } },
		/* [2]                  */ { { 0x0, 0x2C94 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ 4,
		/* [1]                  */ 2,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 2,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 254,
		/* name                 */ "Starport",
		/* stringID_full        */ 255,
		/* wsa                  */ "starport.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ true,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ true,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 128,
		/* hitpoints            */ 500,
		/* fogUncoverRadius     */ 6,
		/* spriteID             */ 75,
		/* buildCredits         */ 500,
		/* buildTime            */ 120,
		/* availableCampaign    */ 6,
		/* structuresRequired   */ 4608,
		/* sortPriority         */ 32,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 12,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 250,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 50,
		/* layout               */ 6,
		/* iconGroup            */ 20,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C75 } },
		/* [1]                  */ { { 0x0, 0x2C76 } },
		/* [2]                  */ { { 0x0, 0x2C78 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 256,
		/* name                 */ "Refinery",
		/* stringID_full        */ 257,
		/* wsa                  */ "refinery.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ true,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 128,
		/* hitpoints            */ 450,
		/* fogUncoverRadius     */ 4,
		/* spriteID             */ 76,
		/* buildCredits         */ 400,
		/* buildTime            */ 80,
		/* availableCampaign    */ 1,
		/* structuresRequired   */ 512,
		/* sortPriority         */ 8,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 13,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 300,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 65536,
		/* creditsStorage       */ 1005,
		/* powerUsage           */ 30,
		/* layout               */ 5,
		/* iconGroup            */ 21,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C86 } },
		/* [1]                  */ { { 0x0, 0x2C87 } },
		/* [2]                  */ { { 0x0, 0x2C89 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 258,
		/* name                 */ "Repair",
		/* stringID_full        */ 259,
		/* wsa                  */ "repair.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 128,
		/* hitpoints            */ 200,
		/* fogUncoverRadius     */ 3,
		/* spriteID             */ 77,
		/* buildCredits         */ 700,
		/* buildTime            */ 80,
		/* availableCampaign    */ 5,
		/* structuresRequired   */ 262664,
		/* sortPriority         */ 24,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 14,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 600,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 130944,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 20,
		/* layout               */ 5,
		/* iconGroup            */ 22,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C8D } },
		/* [1]                  */ { { 0x0, 0x2C8F } },
		/* [2]                  */ { { 0x0, 0x2C90 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 260,
		/* name                 */ "Wall",
		/* stringID_full        */ 261,
		/* wsa                  */ "wall.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ true,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ false,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 0,
		/* hitpoints            */ 50,
		/* fogUncoverRadius     */ 1,
		/* spriteID             */ 78,
		/* buildCredits         */ 50,
		/* buildTime            */ 40,
		/* availableCampaign    */ 4,
		/* structuresRequired   */ 262656,
		/* sortPriority         */ 16,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 15,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 30,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 0,
		/* layout               */ 0,
		/* iconGroup            */ 6,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x0 } },
		/* [1]                  */ { { 0x0, 0x0 } },
		/* [2]                  */ { { 0x0, 0x0 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 262,
		/* name                 */ "Turret",
		/* stringID_full        */ 263,
		/* wsa                  */ "turret.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 64,
		/* hitpoints            */ 200,
		/* fogUncoverRadius     */ 2,
		/* spriteID             */ 79,
		/* buildCredits         */ 125,
		/* buildTime            */ 64,
		/* availableCampaign    */ 5,
		/* structuresRequired   */ 262656,
		/* sortPriority         */ 22,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 16,
		/* priorityBuild        */ 75,
		/* priorityTarget       */ 150,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 10,
		/* layout               */ 0,
		/* iconGroup            */ 23,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x0 } },
		/* [1]                  */ { { 0x0, 0x0 } },
		/* [2]                  */ { { 0x0, 0x0 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 264,
		/* name                 */ "R-Turret",
		/* stringID_full        */ 265,
		/* wsa                  */ "rturret.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 64,
		/* hitpoints            */ 200,
		/* fogUncoverRadius     */ 5,
		/* spriteID             */ 80,
		/* buildCredits         */ 250,
		/* buildTime            */ 96,
		/* availableCampaign    */ 0,
		/* structuresRequired   */ 262656,
		/* sortPriority         */ 26,
		/* upgradeLevelRequired */ 2,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 17,
		/* priorityBuild        */ 100,
		/* priorityTarget       */ 75,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 25,
		/* layout               */ 0,
		/* iconGroup            */ 24,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x0 } },
		/* [1]                  */ { { 0x0, 0x0 } },
		/* [2]                  */ { { 0x0, 0x0 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 266,
		/* name                 */ "Spice Silo",
		/* stringID_full        */ 267,
		/* wsa                  */ "storage.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ true,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 0,
		/* hitpoints            */ 150,
		/* fogUncoverRadius     */ 2,
		/* spriteID             */ 81,
		/* buildCredits         */ 150,
		/* buildTime            */ 48,
		/* availableCampaign    */ 2,
		/* structuresRequired   */ 4608,
		/* sortPriority         */ 12,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 18,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 150,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 1000,
		/* powerUsage           */ 5,
		/* layout               */ 3,
		/* iconGroup            */ 25,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C93 } },
		/* [1]                  */ { { 0x0, 0x2C93 } },
		/* [2]                  */ { { 0x0, 0x2C93 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	},

	{
		{ /* objectInfo */
		/* stringID_abbrev      */ 268,
		/* name                 */ "Outpost",
		/* stringID_full        */ 269,
		/* wsa                  */ "headqrts.wsa",
		{ { /* flags */
		/* hasShadow            */ false,
		/* factory              */ false,
		/* notused_0004         */ false,
		/* variable_0008        */ false,
		/* variable_0010        */ false,
		/* variable_0020        */ false,
		/* hasTurret            */ false,
		/* conquerable          */ false,
		/* variable_0100        */ false,
		/* noMessageOnDeath     */ false,
		/* tabSelectable        */ false,
		/* scriptNoSlowdown     */ false,
		/* targetAir            */ false,
		/* priority             */ false,
		/* notused_4000         */ false
		} },
		/* spawnChance          */ 128,
		/* hitpoints            */ 500,
		/* fogUncoverRadius     */ 10,
		/* spriteID             */ 82,
		/* buildCredits         */ 400,
		/* buildTime            */ 80,
		/* availableCampaign    */ 2,
		/* structuresRequired   */ 512,
		/* sortPriority         */ 10,
		/* upgradeLevelRequired */ 0,
		/* actionsPlayer        */ { 0, 0, 0, 0 },
		/* available            */ 0,
		/* hintStringID         */ 19,
		/* priorityBuild        */ 0,
		/* priorityTarget       */ 275,
		/* availableHouse       */ 63,
		},
		/* enterFilter          */ 0,
		/* creditsStorage       */ 0,
		/* powerUsage           */ 30,
		/* layout               */ 3,
		/* iconGroup            */ 26,
		{ /* animationProc */
		/* [0]                  */ { { 0x0, 0x2C72 } },
		/* [1]                  */ { { 0x0, 0x2C72 } },
		/* [2]                  */ { { 0x0, 0x2C72 } }
		},
		{ /* buildableUnits */
		/* [0]                  */ -1,
		/* [1]                  */ -1,
		/* [2]                  */ -1,
		/* [3]                  */ -1,
		/* [4]                  */ -1,
		/* [5]                  */ -1,
		/* [6]                  */ -1,
		/* [7]                  */ -1,
		},
		{ /* upgradeCampaign */
		/* [0]                  */ 0,
		/* [1]                  */ 0,
		/* [2]                  */ 0,
		},
	}
};
