/* $Id$ */

/** @file src/table/widget.c Windget file table. */

#include <stdio.h>
#include "types.h"

#include "../gui/widget.h"

Widget g_table_windowWidgets[] = {
	{ /* 0 */
		/* next                  */ { { 0x0, 0x0 } },
		/* index                 */ 30,
		/* shortcut              */ 0,
		/* shortcut2             */ 0,
		/* drawModeNormal        */ 1,
		/* drawModeSelected      */ 1,
		/* drawModeDown          */ 1,
		/* variable_0D           */ 0,
		{ { /* flags */
		/* requiresClick         */ true,
		/* variable_0002         */ true,
		/* clickAsHover          */ false,
		/* invisible             */ false,
		/* variable_0010         */ false,
		/* noClickCascade        */ false,
		/* loseSelect            */ true,
		/* variable_0080         */ false,
		/* buttonFilterLeft      */ 4,
		/* buttonFilterRight     */ 4
		} },
		/* drawProcNormal        */ { { 0x0, 0x0 } },
		/* drawProcSelected      */ { { 0x0, 0x0 } },
		/* drawProcDown          */ { { 0x0, 0x0 } },
		/* parentID              */ 0,
		/* offsetX               */ 0,
		/* offsetY               */ 0,
		/* width                 */ 0,
		/* height                */ 0,
		/* fgColourNormal        */ 15,
		/* bgColourNormal        */ 12,
		/* fgColourSelected      */ 15,
		/* bgColourSelected      */ 12,
		/* fgColourDown          */ 15,
		/* bgColourDown          */ 12,
		/* variable_2C           */ 15,
		/* unknown_002D          */ { 12 },
		{ { /* state */
		/* selected              */ false,
		/* hover1                */ false,
		/* hover2                */ false,
		/* selectedLast          */ false,
		/* hover1Last            */ false,
		/* hover2Last            */ false,
		/* variable_0040         */ false,
		/* keySelected           */ false,
		/* buttonState           */ 0,
		} },
		/* clickProc             */ { { 0x0, 0x0 } },
		/* scrollbar             */ { { 0x0, 0x0 } },
		/* stringID              */ 0,
		/* variable_3A           */ 0,
	},
	{ /* 1 */
		/* next                  */ { { 0x0, 0x0 } },
		/* index                 */ 31,
		/* shortcut              */ 0,
		/* shortcut2             */ 0,
		/* drawModeNormal        */ 1,
		/* drawModeSelected      */ 1,
		/* drawModeDown          */ 1,
		/* variable_0D           */ 0,
		{ { /* flags */
		/* requiresClick         */ true,
		/* variable_0002         */ true,
		/* clickAsHover          */ false,
		/* invisible             */ false,
		/* variable_0010         */ false,
		/* noClickCascade        */ false,
		/* loseSelect            */ true,
		/* variable_0080         */ false,
		/* buttonFilterLeft      */ 4,
		/* buttonFilterRight     */ 4
		} },
		/* drawProcNormal        */ { { 0x0, 0x0 } },
		/* drawProcSelected      */ { { 0x0, 0x0 } },
		/* drawProcDown          */ { { 0x0, 0x0 } },
		/* parentID              */ 0,
		/* offsetX               */ 0,
		/* offsetY               */ 0,
		/* width                 */ 0,
		/* height                */ 0,
		/* fgColourNormal        */ 15,
		/* bgColourNormal        */ 12,
		/* fgColourSelected      */ 15,
		/* bgColourSelected      */ 12,
		/* fgColourDown          */ 15,
		/* bgColourDown          */ 12,
		/* variable_2C           */ 15,
		/* unknown_002D          */ { 12 },
		{ { /* state */
		/* selected              */ false,
		/* hover1                */ false,
		/* hover2                */ false,
		/* selectedLast          */ false,
		/* hover1Last            */ false,
		/* hover2Last            */ false,
		/* variable_0040         */ false,
		/* keySelected           */ false,
		/* buttonState           */ 0,
		} },
		/* clickProc             */ { { 0x0, 0x0 } },
		/* scrollbar             */ { { 0x0, 0x0 } },
		/* stringID              */ 0,
		/* variable_3A           */ 0,
	},
	{ /* 2 */
		/* next                  */ { { 0x0, 0x0 } },
		/* index                 */ 32,
		/* shortcut              */ 0,
		/* shortcut2             */ 0,
		/* drawModeNormal        */ 1,
		/* drawModeSelected      */ 1,
		/* drawModeDown          */ 1,
		/* variable_0D           */ 0,
		{ { /* flags */
		/* requiresClick         */ true,
		/* variable_0002         */ true,
		/* clickAsHover          */ false,
		/* invisible             */ false,
		/* variable_0010         */ false,
		/* noClickCascade        */ false,
		/* loseSelect            */ true,
		/* variable_0080         */ false,
		/* buttonFilterLeft      */ 4,
		/* buttonFilterRight     */ 4
		} },
		/* drawProcNormal        */ { { 0x0, 0x0 } },
		/* drawProcSelected      */ { { 0x0, 0x0 } },
		/* drawProcDown          */ { { 0x0, 0x0 } },
		/* parentID              */ 0,
		/* offsetX               */ 0,
		/* offsetY               */ 0,
		/* width                 */ 0,
		/* height                */ 0,
		/* fgColourNormal        */ 15,
		/* bgColourNormal        */ 12,
		/* fgColourSelected      */ 15,
		/* bgColourSelected      */ 12,
		/* fgColourDown          */ 15,
		/* bgColourDown          */ 12,
		/* variable_2C           */ 15,
		/* unknown_002D          */ { 12 },
		{ { /* state */
		/* selected              */ false,
		/* hover1                */ false,
		/* hover2                */ false,
		/* selectedLast          */ false,
		/* hover1Last            */ false,
		/* hover2Last            */ false,
		/* variable_0040         */ false,
		/* keySelected           */ false,
		/* buttonState           */ 0,
		} },
		/* clickProc             */ { { 0x0, 0x0 } },
		/* scrollbar             */ { { 0x0, 0x0 } },
		/* stringID              */ 0,
		/* variable_3A           */ 0,
	},
	{ /* 3 */
		/* next                  */ { { 0x0, 0x0 } },
		/* index                 */ 33,
		/* shortcut              */ 0,
		/* shortcut2             */ 0,
		/* drawModeNormal        */ 1,
		/* drawModeSelected      */ 1,
		/* drawModeDown          */ 1,
		/* variable_0D           */ 0,
		{ { /* flags */
		/* requiresClick         */ true,
		/* variable_0002         */ true,
		/* clickAsHover          */ false,
		/* invisible             */ false,
		/* variable_0010         */ false,
		/* noClickCascade        */ false,
		/* loseSelect            */ true,
		/* variable_0080         */ false,
		/* buttonFilterLeft      */ 4,
		/* buttonFilterRight     */ 4
		} },
		/* drawProcNormal        */ { { 0x0, 0x0 } },
		/* drawProcSelected      */ { { 0x0, 0x0 } },
		/* drawProcDown          */ { { 0x0, 0x0 } },
		/* parentID              */ 0,
		/* offsetX               */ 0,
		/* offsetY               */ 0,
		/* width                 */ 0,
		/* height                */ 0,
		/* fgColourNormal        */ 15,
		/* bgColourNormal        */ 12,
		/* fgColourSelected      */ 15,
		/* bgColourSelected      */ 12,
		/* fgColourDown          */ 15,
		/* bgColourDown          */ 12,
		/* variable_2C           */ 15,
		/* unknown_002D          */ { 12 },
		{ { /* state */
		/* selected              */ false,
		/* hover1                */ false,
		/* hover2                */ false,
		/* selectedLast          */ false,
		/* hover1Last            */ false,
		/* hover2Last            */ false,
		/* variable_0040         */ false,
		/* keySelected           */ false,
		/* buttonState           */ 0,
		} },
		/* clickProc             */ { { 0x0, 0x0 } },
		/* scrollbar             */ { { 0x0, 0x0 } },
		/* stringID              */ 0,
		/* variable_3A           */ 0,
	},
	{ /* 4 */
		/* next                  */ { { 0x0, 0x0 } },
		/* index                 */ 34,
		/* shortcut              */ 0,
		/* shortcut2             */ 0,
		/* drawModeNormal        */ 1,
		/* drawModeSelected      */ 1,
		/* drawModeDown          */ 1,
		/* variable_0D           */ 0,
		{ { /* flags */
		/* requiresClick         */ true,
		/* variable_0002         */ true,
		/* clickAsHover          */ false,
		/* invisible             */ false,
		/* variable_0010         */ false,
		/* noClickCascade        */ false,
		/* loseSelect            */ true,
		/* variable_0080         */ false,
		/* buttonFilterLeft      */ 4,
		/* buttonFilterRight     */ 4
		} },
		/* drawProcNormal        */ { { 0x0, 0x0 } },
		/* drawProcSelected      */ { { 0x0, 0x0 } },
		/* drawProcDown          */ { { 0x0, 0x0 } },
		/* parentID              */ 0,
		/* offsetX               */ 0,
		/* offsetY               */ 0,
		/* width                 */ 0,
		/* height                */ 0,
		/* fgColourNormal        */ 15,
		/* bgColourNormal        */ 12,
		/* fgColourSelected      */ 15,
		/* bgColourSelected      */ 12,
		/* fgColourDown          */ 15,
		/* bgColourDown          */ 12,
		/* variable_2C           */ 15,
		/* unknown_002D          */ { 12 },
		{ { /* state */
		/* selected              */ false,
		/* hover1                */ false,
		/* hover2                */ false,
		/* selectedLast          */ false,
		/* hover1Last            */ false,
		/* hover2Last            */ false,
		/* variable_0040         */ false,
		/* keySelected           */ false,
		/* buttonState           */ 0,
		} },
		/* clickProc             */ { { 0x0, 0x0 } },
		/* scrollbar             */ { { 0x0, 0x0 } },
		/* stringID              */ 0,
		/* variable_3A           */ 0,
	},
	{ /* 5 */
		/* next                  */ { { 0x0, 0x0 } },
		/* index                 */ 35,
		/* shortcut              */ 0,
		/* shortcut2             */ 0,
		/* drawModeNormal        */ 1,
		/* drawModeSelected      */ 1,
		/* drawModeDown          */ 1,
		/* variable_0D           */ 0,
		{ { /* flags */
		/* requiresClick         */ true,
		/* variable_0002         */ true,
		/* clickAsHover          */ false,
		/* invisible             */ false,
		/* variable_0010         */ false,
		/* noClickCascade        */ false,
		/* loseSelect            */ true,
		/* variable_0080         */ false,
		/* buttonFilterLeft      */ 4,
		/* buttonFilterRight     */ 4
		} },
		/* drawProcNormal        */ { { 0x0, 0x0 } },
		/* drawProcSelected      */ { { 0x0, 0x0 } },
		/* drawProcDown          */ { { 0x0, 0x0 } },
		/* parentID              */ 0,
		/* offsetX               */ 0,
		/* offsetY               */ 0,
		/* width                 */ 0,
		/* height                */ 0,
		/* fgColourNormal        */ 15,
		/* bgColourNormal        */ 12,
		/* fgColourSelected      */ 15,
		/* bgColourSelected      */ 12,
		/* fgColourDown          */ 15,
		/* bgColourDown          */ 12,
		/* variable_2C           */ 15,
		/* unknown_002D          */ { 12 },
		{ { /* state */
		/* selected              */ false,
		/* hover1                */ false,
		/* hover2                */ false,
		/* selectedLast          */ false,
		/* hover1Last            */ false,
		/* hover2Last            */ false,
		/* variable_0040         */ false,
		/* keySelected           */ false,
		/* buttonState           */ 0,
		} },
		/* clickProc             */ { { 0x0, 0x0 } },
		/* scrollbar             */ { { 0x0, 0x0 } },
		/* stringID              */ 0,
		/* variable_3A           */ 0,
	},
	{ /* 6 */
		/* next                  */ { { 0x0, 0x0 } },
		/* index                 */ 36,
		/* shortcut              */ 0,
		/* shortcut2             */ 0,
		/* drawModeNormal        */ 1,
		/* drawModeSelected      */ 1,
		/* drawModeDown          */ 1,
		/* variable_0D           */ 0,
		{ { /* flags */
		/* requiresClick         */ true,
		/* variable_0002         */ true,
		/* clickAsHover          */ false,
		/* invisible             */ false,
		/* variable_0010         */ false,
		/* noClickCascade        */ false,
		/* loseSelect            */ true,
		/* variable_0080         */ false,
		/* buttonFilterLeft      */ 4,
		/* buttonFilterRight     */ 4
		} },
		/* drawProcNormal        */ { { 0x0, 0x0 } },
		/* drawProcSelected      */ { { 0x0, 0x0 } },
		/* drawProcDown          */ { { 0x0, 0x0 } },
		/* parentID              */ 0,
		/* offsetX               */ 0,
		/* offsetY               */ 0,
		/* width                 */ 0,
		/* height                */ 0,
		/* fgColourNormal        */ 15,
		/* bgColourNormal        */ 12,
		/* fgColourSelected      */ 15,
		/* bgColourSelected      */ 12,
		/* fgColourDown          */ 15,
		/* bgColourDown          */ 12,
		/* variable_2C           */ 15,
		/* unknown_002D          */ { 12 },
		{ { /* state */
		/* selected              */ false,
		/* hover1                */ false,
		/* hover2                */ false,
		/* selectedLast          */ false,
		/* hover1Last            */ false,
		/* hover2Last            */ false,
		/* variable_0040         */ false,
		/* keySelected           */ false,
		/* buttonState           */ 0,
		} },
		/* clickProc             */ { { 0x0, 0x0 } },
		/* scrollbar             */ { { 0x0, 0x0 } },
		/* stringID              */ 0,
		/* variable_3A           */ 0,
	},
	{ /* 7 */
		/* next                  */ { { 0x0, 0x0 } },
		/* index                 */ 37,
		/* shortcut              */ 96,
		/* shortcut2             */ 0,
		/* drawModeNormal        */ 1,
		/* drawModeSelected      */ 1,
		/* drawModeDown          */ 1,
		/* variable_0D           */ 0,
		{ { /* flags */
		/* requiresClick         */ true,
		/* variable_0002         */ true,
		/* clickAsHover          */ true,
		/* invisible             */ false,
		/* variable_0010         */ false,
		/* noClickCascade        */ false,
		/* loseSelect            */ false,
		/* variable_0080         */ true,
		/* buttonFilterLeft      */ 4,
		/* buttonFilterRight     */ 4
		} },
		/* drawProcNormal        */ { { 0x0, 0x0 } },
		/* drawProcSelected      */ { { 0x0, 0x0 } },
		/* drawProcDown          */ { { 0x0, 0x0 } },
		/* parentID              */ 17,
		/* offsetX               */ 128,
		/* offsetY               */ 20,
		/* width                 */ 25,
		/* height                */ 16,
		/* fgColourNormal        */ 15,
		/* bgColourNormal        */ 12,
		/* fgColourSelected      */ 15,
		/* bgColourSelected      */ 12,
		/* fgColourDown          */ 15,
		/* bgColourDown          */ 12,
		/* variable_2C           */ 15,
		/* unknown_002D          */ { 12 },
		{ { /* state */
		/* selected              */ false,
		/* hover1                */ false,
		/* hover2                */ false,
		/* selectedLast          */ false,
		/* hover1Last            */ false,
		/* hover2Last            */ false,
		/* variable_0040         */ false,
		/* keySelected           */ false,
		/* buttonState           */ 0,
		} },
		/* clickProc             */ { { 0x0, 0x0 } },
		/* scrollbar             */ { { 0x0, 0x0 } },
		/* stringID              */ 0,
		/* variable_3A           */ 0,
	},
	{ /* 8 */
		/* next                  */ { { 0x0, 0x0 } },
		/* index                 */ 38,
		/* shortcut              */ 98,
		/* shortcut2             */ 0,
		/* drawModeNormal        */ 1,
		/* drawModeSelected      */ 1,
		/* drawModeDown          */ 1,
		/* variable_0D           */ 0,
		{ { /* flags */
		/* requiresClick         */ true,
		/* variable_0002         */ true,
		/* clickAsHover          */ true,
		/* invisible             */ false,
		/* variable_0010         */ false,
		/* noClickCascade        */ false,
		/* loseSelect            */ false,
		/* variable_0080         */ true,
		/* buttonFilterLeft      */ 4,
		/* buttonFilterRight     */ 4
		} },
		/* drawProcNormal        */ { { 0x0, 0x0 } },
		/* drawProcSelected      */ { { 0x0, 0x0 } },
		/* drawProcDown          */ { { 0x0, 0x0 } },
		/* parentID              */ 17,
		/* offsetX               */ 128,
		/* offsetY               */ 126,
		/* width                 */ 25,
		/* height                */ 16,
		/* fgColourNormal        */ 15,
		/* bgColourNormal        */ 12,
		/* fgColourSelected      */ 15,
		/* bgColourSelected      */ 12,
		/* fgColourDown          */ 15,
		/* bgColourDown          */ 12,
		/* variable_2C           */ 15,
		/* unknown_002D          */ { 12 },
		{ { /* state */
		/* selected              */ false,
		/* hover1                */ false,
		/* hover2                */ false,
		/* selectedLast          */ false,
		/* hover1Last            */ false,
		/* hover2Last            */ false,
		/* variable_0040         */ false,
		/* keySelected           */ false,
		/* buttonState           */ 0,
		} },
		/* clickProc             */ { { 0x0, 0x0 } },
		/* scrollbar             */ { { 0x0, 0x0 } },
		/* stringID              */ 0,
		/* variable_3A           */ 0,
	}
};
