/** @file include/libemu_math.h Emulated math routines. */

extern void emu_boundb(uint8 reg, uint8 *bound);
extern void emu_boundw(uint16 reg, uint16 *bound);
extern void emu_addb(uint8 *dest, uint8 val2);
extern void emu_addw(uint16 *dest, uint16 val2);
extern void emu_addws(uint16 *dest, int8 val2);
extern void emu_adcb(uint8 *dest, uint8 val2);
extern void emu_adcw(uint16 *dest, uint16 val2);
extern void emu_adcws(uint16 *dest, int8 val2);
extern void emu_subb(uint8 *dest, uint8 val2);
extern void emu_subw(uint16 *dest, uint16 val2);
extern void emu_subws(uint16 *dest, int8 src);
extern void emu_sbbb(uint8 *dest, uint8 val2);
extern void emu_sbbw(uint16 *dest, uint16 val2);
extern void emu_sbbws(uint16 *dest, int8 src);
extern void emu_incb(uint8 *dest);
extern void emu_incw(uint16 *dest);
extern void emu_decb(uint8 *dest);
extern void emu_decw(uint16 *dest);
extern void emu_cmpb(uint8 *dest, uint8 val2);
extern void emu_cmpw(uint16 *dest, uint16 val2);
extern void emu_cmpws(uint16 *dest, int8 src);
extern void emu_andb(uint8 *dest, uint8 val2);
extern void emu_andw(uint16 *dest, uint16 val2);
extern void emu_andws(uint16 *dest, int8 val2);
extern void emu_testb(uint8 *dest, uint8 val2);
extern void emu_testw(uint16 *dest, uint16 val2);
extern void emu_testws(uint16 *dest, int8 val2);
extern void emu_orb(uint8 *dest, uint8 val2);
extern void emu_orw(uint16 *dest, uint16 val2);
extern void emu_orws(uint16 *dest, int8 val2);
extern void emu_xorb(uint8 *dest, uint8 val2);
extern void emu_xorw(uint16 *dest, uint16 val2);
extern void emu_xorws(uint16 *dest, int8 val2);
extern void emu_negb(uint8 *dest, uint8 val2);
extern void emu_negw(uint16 *dest, uint16 val2);
extern void emu_negws(uint16 *dest, int8 val2);
extern void emu_notb(uint8 *dest, uint8 val2);
extern void emu_notw(uint16 *dest, uint16 val2);
extern void emu_notws(uint16 *dest, int8 val2);
extern void emu_mulb(uint8 *dest, uint8 val2);
extern void emu_mulw(uint16 *dest, uint16 val2);
extern void emu_mulws(uint16 *dest, int8 src);
extern void emu_imulb(uint8 *dest, int8 val1, int8 val2);
extern void emu_imulw(uint16 *dest, int16 val1, int16 val2);
extern void emu_imulub(uint8 *dest, int8 val);
extern void emu_imuluw(uint16 *dest, int16 val);
extern void emu_divb(uint8 *dest, uint8 val2);
extern void emu_divw(uint16 *dest, uint16 val2);
extern void emu_idivb(uint8 *dest, int8 val2);
extern void emu_idivw(uint16 *dest, int16 val2);
extern void emu_shlb(uint8 *dest, uint8 val2);
extern void emu_shlw(uint16 *dest, uint16 val2);
extern void emu_shlws(uint16 *dest, int8 val2);
extern void emu_shrb(uint8 *dest, uint8 val2);
extern void emu_shrw(uint16 *dest, uint16 val2);
extern void emu_shrws(uint16 *dest, int8 val2);
extern void emu_sarb(uint8 *dest, uint8 val2);
extern void emu_sarw(uint16 *dest, uint16 val2);
extern void emu_sarws(uint16 *dest, int8 val2);
extern void emu_rolb(uint8 *dest, uint8 val2);
extern void emu_rolw(uint16 *dest, uint16 val2);
extern void emu_rolws(uint16 *dest, int8 val2);
extern void emu_rorb(uint8 *dest, uint8 val2);
extern void emu_rorw(uint16 *dest, uint16 val2);
extern void emu_rorws(uint16 *dest, int8 val2);
extern void emu_rclb(uint8 *dest, uint8 val2);
extern void emu_rclw(uint16 *dest, uint16 val2);
extern void emu_rclws(uint16 *dest, int8 val2);
extern void emu_rcrb(uint8 *dest, uint8 val2);
extern void emu_rcrw(uint16 *dest, uint16 val2);
extern void emu_rcrws(uint16 *dest, int8 val2);
extern void emu_aaa();
extern void emu_aad();
extern void emu_aam();
extern void emu_aas();
extern void emu_daa();
extern void emu_das();
